runtime: nodejs
env: flex

handlers:
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
  
  - url: /
    static_dir: dist

automatic_scaling:
  # target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 42  # Adjust this value
